/*
테이블 : CAR_RENTAL_COMPANY_RENTAL_HISTORY
출력 컬럼 : *, (END_DATE - START_DATE) AS RENT_TYPE
조건)
CASE
    WHEN DATEDIFF(END_DATE, START_DATE) >= 30 THEN '장기 대여'
    # 실질적인 기간은 두 날짜의 차에서 1을 더해야 함!
    ELSE '단기 대여'
    END
WHERE START_DATE LIKE '2022-09%'
ORDER BY HISTORY_ID DESC
*/

SELECT HISTORY_ID,
    CAR_ID,
    DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE,
    DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE,
    CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '장기 대여'
    ELSE '단기 대여' END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE LIKE '2022-09%'
ORDER BY HISTORY_ID DESC;
