/*
테이블 : FOOD_WAREHOUSE
출력 컬럼 : WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, FREEZER_YN
조건) COLEASE(FREEZER_YN, 'N')
ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID
*/

SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID
