/*
참조되는 테이블 : DOCTOR
출력할 컬럼 : DR_NAME, DR_ID, MCDP_CD, HIRE_YMD
HIRE_YMD의 날짜 포맷 => '%Y-%m-%d'
조건 : MCDP_CD가 CS OR GS
정렬 : HIRE_YMD DESC, DR_NAME ASC
*/

SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, '%Y-%m-%d')
FROM DOCTOR
WHERE MCDP_CD IN ('CS', 'GS')
ORDER BY HIRE_YMD DESC, DR_NAME;
