/*
테이블 : ANIMAL_INS
출력 컬럼 : NAME
조건) DATETIME이 가장 작은 값의 컬럼
=> DATETIME = (SELECT MIN(DATETIME) FROM ANIMALS_INS)
*/

/* [Solution 1]
SELECT NAME
FROM ANIMAL_INS
WHERE DATETIME = (SELECT MIN(DATETIME) FROM ANIMAL_INS);
*/

# [Solution 2]
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME LIMIT 1;
