/*
테이블 : PATIENT
출력 컬럼: PT_NAME, PT_NO, GEND_CD, AGE, TLNO=>COALESCE(TLNO, 'NONE')
조건) 
AGE <= 12, GEND_CD = 'W'
COALESC(TLNO, 'NONE')
null일 때 출력값 정하는 함수 => IFNULL(COLUMN, '문구'), COALESCE()
ORDER BY AGE DESC, PT_NAME
*/

SELECT PT_NAME, PT_NO, GEND_CD, AGE, COALESCE(TLNO, 'NONE') AS TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME
