/*
테이블 : ANIMAL_INS
컬럼 : MAX(DATETIME) AS 시간
*/

# MySQL, Oracle
SELECT MAX(DATETIME) AS 시간
FROM ANIMAL_INS;

# Oracle Only
SELECT DATETIME AS 시간
FROM (SELECT * FROM ANIMAL_INS ORDER BY DATETIME DESC)
WHERE ROWNUM <=1;
