/*
테이블 : FISH_INFO AS A, FISH_NAME_INFO AS B
출력 컬럼 : ID, FISH_NAME, LENGTH
조건) 
ORDER BY ID
*/

SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS A LEFT JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.FISH_TYPE IN
(
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)  
)
ORDER BY ID