/*
테이블 : SUBWAY_DISTANCE
출력 컬럼 : ROUTE, ROUND(SUM(D_BETWEEN_DIST), 1) AS TOTAL_DISTANCE, ROUND(AVG(D_BETWEEN_DIST), 2) AS AVERAGE_DISTANCE
조건) GROUP BY ROUTE
ORDER BY TOTAL_DISTANCE DESC
*/

SELECT ROUTE, 
CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE, 
CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(SUM(D_BETWEEN_DIST), 1) DESC;
