/*
테이블 : ITEM_INFO A INNER JOIN ITEM_TREE B
출력 컬럼 : A.ITEM_ID, A.ITEM_NAME
조건) WHERE A.ITEM_ID = B.ITEM_ID
AND B.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID DESC;
*/

SELECT A.ITEM_ID, A.ITEM_NAME
FROM ITEM_INFO A INNER JOIN ITEM_TREE B
WHERE A.ITEM_ID = B.ITEM_ID
AND B.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID;
