/*
테이블 : ANIMAL_INS
출력 컬럼 : NAME, COUNT(NAME) AS COUNT
조건) 
COUNT(NAME) >= 2
GROUP BY NAME
ORDER BY NAME;
*/

SELECT NAME, COUNT(*) AS COUNT
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME HAVING COUNT(*)>=2
ORDER BY NAME;