/*
테이블명 : ANIMAL_OUTS
출력 컬럼명 : HOUR, COUNT(*) AS COUNT
조건) TO_CHAR(DATETIME,'HH24') AS HOUR
GROUP BY TO_CHAR(DATETIME,'HH24') AS HOUR
ORDER BY HOUR
*/

SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR>=9 AND HOUR<=19
ORDER BY HOUR;