/*
테이블 : HR_DEPARTMENT D, HR_EMPLOYEES E, HR_GRADE G
출력 컬럼 : SUM(SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
 조건) E.EMPNO = G.EMPNO
 YEAR = '2022'
 ORDER BY SCORE DESC LIMIT 1
*/

SELECT SUM(SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E INNER JOIN HR_GRADE G
ON E.EMP_NO = G.EMP_NO
GROUP BY YEAR, EMP_NO
HAVING G.YEAR = '2022'
ORDER BY SCORE DESC
LIMIT 1;
