/*
테이블 : FISH_INFO INNER JOIN FISH_NAME_INFO
출력 컬럼 : COUNT(*) AS FISH_COUNT, FISH_NAME
조건) 
GROUP BY FISH_NAME
HAVING FISH_TYPE = FISH_NAME
ORDER BY FISH_COUNT
*/

SELECT COUNT(*) AS FISH_COUNT, N.FISH_NAME
FROM FISH_INFO I INNER JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
GROUP BY N.FISH_NAME
ORDER BY 1 DESC;