/*
테이블 : CAR_RENTAL_COMPANY
출력 컬럼 : CAR_TYPE, COUNT(*) AS CARS
조건)
OPTIONS에서 가죽시트 OR 열선시트 OR 통풍시트
ORDER BY CAR_TYPE
*/

# SOLUTION 1
SELECT CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%가죽시트%' OR OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%통풍시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE;

# SOLUTION 2
SELECT CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS REGEXP '가죽시트|열선시트|통풍시트'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE;
