/*
테이블 : ANIMAL_INS
컬럼 : ANIMAL_TYPE, COUNT(ANIMAL_ID) AS count
조건)
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE
*/

SELECT ANIMAL_TYPE, COUNT(ANIMAL_ID) AS count
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE;
