/*
테이블 : FISH_INFO
출력 컬럼 : COUNT(*) AS FISH_COUNT, CAST(SUBSTRING(TIME, 6, 2) AS INT) AS MONTH
조건) 
GROUP BY MONTH
ORDER BY MONTH
*/

SELECT  COUNT(ID) AS FISH_COUNT, MONTH(TIME) AS MONTH
FROM FISH_INFO
GROUP BY MONTH(TIME)
ORDER BY MONTH ASC;
