/*
테이블 : PRODUCT, OFFLINE_SALE
출력 컬럼 : PRODUCT_CODE, SALES
*/

SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT P RIGHT OUTER JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE;