/*
테이블 : BOOK AS B, AUTHOR AS A
출력 컬럼 : BOOK_ID, AUTHOR_NAME, PUBLISHED_DATE
조건) 
B.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE
B.AUTHOR_ID = A.AUTHOR_ID
*/

SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS B INNER JOIN AUTHOR AS A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE;
