/*
테이블 : MEMBER_PROFILE
출력 컬럼 : MEMBER_ID, MEMBER_NAME, GENDER, DATE_OF_BIRTH
조건) 
DATE_OF_BIRTH LIKE '%-03-%'
GENDER = 'W'
TLNO IS NOT NULL
ORDER BY MEMBER_ID
*/

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL
AND DATE_OF_BIRTH LIKE '%-03-%'
AND GENDER = 'W'
ORDER BY MEMBER_ID;
