/*
테이블 : ITEM INFO AS A, ITEM_TREE AS B, ITEM_TREE AS C
출력 컬럼 : C.ITEM_ID, A.ITEM_NAME, A.RARITY
조건) RARITY = 'RARE'
ITEM_ID = PARENT_ITEM_ID
서브쿼리로 rarity가 rare인 아이템 아이디들을 조회해서 
그 아이디와 parent_item_id가 같은 아이템의 아이디를 출력
*/

SELECT B.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO AS A INNER JOIN ITEM_TREE AS B
ON A.ITEM_ID = B.ITEM_ID
WHERE B.PARENT_ITEM_ID IN 
(SELECT ITEM_ID FROM ITEM_INFO 
 WHERE RARITY = "RARE")
ORDER BY A.ITEM_ID DESC;
