/*
테이블 : FISH_INFO AS FI LEFT JOIN FISH_NAME_INFO AS FN
출력 컬럼 : COUNT(*) AS FISH_COUNT
조건) FN.FISH_NAME IN ('BASS', 'SNAPPER')
*/

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO AS FI INNER JOIN FISH_NAME_INFO AS FN
ON FI.FISH_TYPE = FN.FISH_TYPE
WHERE FN.FISH_NAME IN ('BASS', 'SNAPPER');
