/*
테이블 : ECOLI_DATA
출력 컬럼 : ID, GENOTYPE, PARENT_GENOTYPE
조건) 부모의 형질을 모두 보유 =>
이진수의 자릿수 비교 판별 => &, |, ^
부모의 GENOTYPE 와 GENOTYPE의 연관관계도 파악해야 함
WHERE PARENT_GENOTYPE & GENOTYPE = PARENT_GENOTYPE
ORDER BY ID;
*/

SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA A INNER JOIN ECOLI_DATA B
ON A.PARENT_ID = B.ID
WHERE B.GENOTYPE = (A.GENOTYPE & B.GENOTYPE)
ORDER BY A.ID;
