/*
테이블 : ECOLI_DATA
출력 컬럼 : 
CONCAT(CEIL(MONTH(DIFFERENTIATION_DATE) / 3), 'Q') AS QUARTER, COUNT(ID) AS ECOLI_COUNT
조건)
GROUP BY QUARTER
ORDER BY QUARTER
*/

SELECT CONCAT(CEIL(MONTH(DIFFERENTIATION_DATE) / 3), 'Q') AS QUARTER, COUNT(ID) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER;
