/*
테이블 : USER_GOODS_BOARD
출력 컬럼 : BOARD_ID, WRITER_ID, TITLE, PRICE, 
CASE WHEN STATUS = 'DONE' THEN '거래완료'
     ELSE '판매중' END AS STATUS
조건) 
ORDER BY BOARD_ID DESC;
*/

SELECT 
BOARD_ID, 
WRITER_ID, 
TITLE, 
PRICE, 
CASE WHEN STATUS = 'DONE' THEN '거래완료'
     WHEN STATUS = 'RESERVED' THEN '예약중'
     WHEN STATUS = 'SALE' THEN '판매중' 
     END AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = '2022-10-05'
ORDER BY BOARD_ID DESC;