/*
테이블 : FOOD_PRODUCT
출력 컬럼 : *
조건) 
ORDER BY PRICE DESC LIMIT 1;
*/

# SOLUTION 1
SELECT * FROM FOOD_PRODUCT
ORDER BY PRICE DESC LIMIT 1;

# SOLUTION 2
SELECT * FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE)
               FROM FOOD_PRODUCT);
